[workspace]
resolver = "1"
members = ["crates/*"]

[workspace.dependencies]
anyhow = { version = "1.0" }
cargo_metadata = { version = "0.19" }
clap = { version = "4.5", features = ["derive"] }
git2 = { version = "0.20.2" }
thiserror = { version = "2.0" }
tracing = { version = "0.1.41" }
