[package]
name = "affected"
description = ""
version = "0.0.1"
edition = "2024"

[dependencies]
sources = { path = "../sources" }
workspace = { path = "../workspace" }
thiserror = { workspace = true }
